"""Frame-relationship audit. No transforms are applied in Stage 0."""

from __future__ import annotations

from typing import Any

FRAME_COLUMNS = [
    "dataset",
    "quantity",
    "source_topic_or_file",
    "source_frame",
    "target/reference_frame",
    "transform_available",
    "transform_type",
    "translation",
    "rotation_representation",
    "quaternion_order",
    "axis_convention",
    "evidence_source",
    "confidence",
    "notes",
]


def frame_row(**kwargs: Any) -> dict[str, Any]:
    row = {key: kwargs.get(key, "") for key in FRAME_COLUMNS}
    return row


def blackbird_documented_frames() -> list[dict[str, Any]]:
    """From official papers + official converter settings.json. No conversion executed."""
    return [
        frame_row(
            dataset="BLACKBIRD",
            quantity="motion_capture_pose",
            source_topic_or_file="/blackbird/state (LCM poseMoCap)",
            source_frame="mocap_NED",
            **{"target/reference_frame": "world/mocap"},
            transform_available="IDENTITY_IN_MOCAP",
            transform_type="pose_in_mocap_NED",
            translation="position in mocap",
            rotation_representation="quaternion_from_LCM_orient_wxyz_in_converter",
            quaternion_order="LCM orient[0]=w, orient[1]=x, orient[2]=y, orient[3]=z (official converter)",
            axis_convention="NED documented in dataset paper; converter comments mention mocap_NED",
            evidence_source="VERIFIED_FROM_DATASET_PAPER + VERIFIED_FROM_OFFICIAL_SOURCE_CODE",
            confidence="HIGH",
            notes="Paper: ground-truth is NED. Converter publishes PoseStamped on /blackbird/state with frame_id mocap.",
        ),
        frame_row(
            dataset="BLACKBIRD",
            quantity="body_pose_from_mocap",
            source_topic_or_file="/tf child body_frame",
            source_frame="body_frame",
            **{"target/reference_frame": "mocap_NED"},
            transform_available="YES_IN_CONVERTER",
            transform_type="time-varying TF mocap_NED -> body_frame",
            translation="same as pose.position",
            rotation_representation="quaternion",
            quaternion_order="ROS geometry_msgs (x,y,z,w on the message; LCM source is wxyz)",
            axis_convention="Paper Fig 1: Camera_D coincident with Body Frame. IMU is a distinct sensor frame in Fig 1.",
            evidence_source="VERIFIED_FROM_OFFICIAL_SOURCE_CODE + VERIFIED_FROM_DATASET_PAPER",
            confidence="HIGH",
            notes="Body frame is not automatically the IMU frame.",
        ),
        frame_row(
            dataset="BLACKBIRD",
            quantity="imu_measurement_frame",
            source_topic_or_file="/blackbird/imu",
            source_frame="imu",
            **{"target/reference_frame": "body_frame"},
            transform_available="NO_UNCOMMENTED_OFFICIAL_TF",
            transform_type="FRAME_RELATION_UNRESOLVED",
            translation="commented converter draft used zeros; not treated as published",
            rotation_representation="commented quaternion in converter is NOT used",
            quaternion_order="UNRESOLVED",
            axis_convention="header.frame_id=imu in official settings.json; Fig 1 shows a separate IMU triad",
            evidence_source="VERIFIED_FROM_OFFICIAL_SOURCE_CODE",
            confidence="MEDIUM",
            notes="A commented IMU TF exists in msgConverters.py. Stage 0 does not treat commented code as a released calibration. Kalibr IMU-camera file lives on the data host, which is unavailable.",
        ),
        frame_row(
            dataset="BLACKBIRD",
            quantity="imu_to_camera",
            source_topic_or_file="Kalibr calibration on data host /cameraCalibration/",
            source_frame="imu",
            **{"target/reference_frame": "camera"},
            transform_available="DOCUMENTED_BUT_FILE_NOT_RETRIEVABLE",
            transform_type="Kalibr IMU-camera (paper)",
            translation="UNRESOLVED",
            rotation_representation="UNRESOLVED",
            quaternion_order="UNRESOLVED",
            axis_convention="UNRESOLVED",
            evidence_source="VERIFIED_FROM_DATASET_PAPER",
            confidence="LOW",
            notes="Paper states Kalibr was used. GitHub issue 12 reports the CSV is on the data server. Server currently unavailable.",
        ),
    ]


def uzh_documented_frames() -> list[dict[str, Any]]:
    return [
        frame_row(
            dataset="UZH_FPV",
            quantity="leica_prism_position",
            source_topic_or_file="Leica Nova MS60 / official raw Leica zip",
            source_frame="P (prism)",
            **{"target/reference_frame": "W (world, gravity-aligned, leveled tripod)"},
            transform_available="POSITION_ONLY",
            transform_type="range-bearing tracker of prism",
            translation="p_W_P",
            rotation_representation="none",
            quaternion_order="n/a",
            axis_convention="Paper Fig 6: W gravity-aligned; red/green/blue = x/y/z. Right-handed implied by figure, not explicitly labeled left/right-handed in text.",
            evidence_source="VERIFIED_FROM_DATASET_PAPER",
            confidence="HIGH",
            notes="Leica measures prism position, not IMU pose.",
        ),
        frame_row(
            dataset="UZH_FPV",
            quantity="snapdragon_imu",
            source_topic_or_file="/snappy_imu (rosbag) or imu.txt (zip)",
            source_frame="S (Snapdragon IMU)",
            **{"target/reference_frame": "S"},
            transform_available="IDENTITY_IN_SENSOR_FRAME",
            transform_type="sensor_msgs/Imu in sensor frame S",
            translation="0",
            rotation_representation="n/a for vector measurements",
            quaternion_order="n/a",
            axis_convention="Paper Fig 6 defines S; Kalibr T_cam_imu relates C to S",
            evidence_source="VERIFIED_FROM_DATASET_PAPER + VERIFIED_FROM_OFFICIAL_SOURCE_CODE",
            confidence="HIGH",
            notes="DAVIS IMU is frame D, not interchangeable with S.",
        ),
        frame_row(
            dataset="UZH_FPV",
            quantity="davis_imu",
            source_topic_or_file="/dvs/imu",
            source_frame="D (mDAVIS IMU)",
            **{"target/reference_frame": "D"},
            transform_available="IDENTITY_IN_SENSOR_FRAME",
            transform_type="separate IMU",
            translation="0",
            rotation_representation="n/a",
            quaternion_order="n/a",
            axis_convention="Paper Fig 6",
            evidence_source="VERIFIED_FROM_DATASET_PAPER + VERIFIED_FROM_OFFICIAL_SOURCE_CODE",
            confidence="HIGH",
            notes="Stage 0 standardizes on Snapdragon; DAVIS is inventoried but not treated as the same IMU.",
        ),
        frame_row(
            dataset="UZH_FPV",
            quantity="camera_to_snapdragon_imu",
            source_topic_or_file="Kalibr YAML in official calib zip",
            source_frame="C (Snapdragon camera)",
            **{"target/reference_frame": "S (Snapdragon IMU)"},
            transform_available="YES_IF_CALIB_ZIP_DOWNLOADED",
            transform_type="Kalibr T_cam_imu 4x4",
            translation="from YAML",
            rotation_representation="4x4 homogeneous in Kalibr YAML",
            quaternion_order="not used; rotation matrix in T_cam_imu",
            axis_convention="Kalibr convention T_cam_imu",
            evidence_source="VERIFIED_FROM_OFFICIAL_DOCUMENTATION",
            confidence="HIGH",
            notes="Inspected from downloaded YAML when present.",
        ),
        frame_row(
            dataset="UZH_FPV",
            quantity="public_ground_truth_pose",
            source_topic_or_file="geometry_msgs/PoseStamped or zip groundtruth text; official min-bag uses /groundtruth/odometry",
            source_frame="estimated IMU frame pose vs W",
            **{"target/reference_frame": "W"},
            transform_available="YES_AS_POSE_FILE",
            transform_type="batch ML pose (Leica position + IMU)",
            translation="position of IMU frame in W",
            rotation_representation="quaternion in Pose message",
            quaternion_order="ROS Pose (x,y,z,w) if from bag; text file order inspected from file",
            axis_convention="W from Fig 6",
            evidence_source="VERIFIED_FROM_DATASET_PAPER + VERIFIED_FROM_OFFICIAL_SOURCE_CODE",
            confidence="HIGH",
            notes="Public 6-DoF GT is NOT independent of IMU. Orientation is estimated, not directly measured by Leica.",
        ),
        frame_row(
            dataset="UZH_FPV",
            quantity="blackbird_to_uzh_common_body",
            source_topic_or_file="n/a",
            source_frame="Blackbird imu/body",
            **{"target/reference_frame": "UZH Snapdragon S"},
            transform_available="NO",
            transform_type="FRAME_RELATION_UNRESOLVED",
            translation="",
            rotation_representation="",
            quaternion_order="",
            axis_convention="different vehicles; no official cross-dataset extrinsic",
            evidence_source="Stage-0 rule: do not invent a transform",
            confidence="HIGH",
            notes="No documented deterministic Blackbird→UZH body convention exists. A later common body frame would require an explicit, justified convention, not a fitted warp on test data.",
        ),
    ]
